import os
from dotenv import load_dotenv

# Load the API key from the .env file
load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')
if not api_key:
    raise ValueError("API key not found. Please set the OPENAI_API_KEY environment variable.")


# -*- coding: utf-8 -*-
"""Ben_MIT Intro Coding Translation 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3nyNpK8RzN3pMYhgY6i4A1ZxY7WODYp
"""

# Install the necessary libraries (if not already installed)


# Import necessary libraries
import openai
import os
from dotenv import load_dotenv

# Load the API key from the .env file
load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')

# Debugging: Print environment variables to check if they are loaded correctly
print(f"API Key: {api_key}")

if not api_key:
    raise ValueError("API key not found. Please set the OPENAI_API_KEY environment variable.")

# Initialize the OpenAI client
client = openai.OpenAI(api_key=api_key)

# Define the translation function
def translate_to_french(text):
    prompt = f"Translate the following English text to French:\n\n{text}"
    response = client.completions.create(
        model="gpt-3.5-turbo-instruct",  # Use the appropriate model
        prompt=prompt,
        max_tokens=100,
        temperature=0.5,
    )
    translation = response.choices[0].text.strip()
    return translation

# Test the translation function
english_text = "Hello, how are you doing today?"
french_translation = translate_to_french(english_text)
print(f"English: {english_text}")
print(f"French: {french_translation}")

